app/blog/urls.py
from django.conf.urls import url

from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView

urlpatterns = [
    url(r'^post/$', PostListView.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', PostCreateView.as_view(), name='post_new'),
    url(r'^post/edit/(?P<pk>\d+)/$', PostUpdateView.as_view(), name='post_edit'),
]

app/nucleus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    # Add documentation functionality.
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    # Added link to all the urls accessed by the blog app.
    url(r'', include('blog.urls')),
    url(r'', include('class_management.urls')),

]

# Added path to img - AKSHAY GAUR
# https://docs.djangoproject.com/en/2.0/howto/static-files/
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/class_management/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# from django.db import models

# Create your models here.
from django.db.models import Model, CharField, ForeignKey, IntegerField, TextField, ManyToManyField, DecimalField, \
    BooleanField, ImageField
from django.urls import reverse

from nucleus.settings import MEDIA_URL


class Department(Model):
    """
    Model that stores the department details.
    Primary key is the department key.
    """
    class Meta:
        db_table = "departments"
        ordering = ['department_name']
    department_name = CharField(max_length=200)
    department_code = CharField(max_length=5, primary_key=True)
    department_chair = CharField(max_length=200)

    def __unicode__(self):
        """
        String representation of the object.
        :return: Department name in unicode.
        """
        return self.department_name


class Course(Model):
    """
    Model to store the course details.
    The primary key is a compound key (combination of department code and course number).
    """
    class Meta:
        """
        Defines the compound primary key for this object.
        Also defines the table name for the object.
        """
        unique_together = (('course_dept_code', 'course_num_code'), )
        db_table = 'courses'
    course_dept_code = ForeignKey(Department)
    course_num_code = IntegerField()
    course_name = CharField(max_length=200)
    course_seats = IntegerField()
    course_description = TextField(blank=True)

    def __unicode__(self):
        return self.course_name


class Student(Model):
    """
    Model to store the student details.
    The primary key is the student id.
    """
    class Meta:
        """
        Defines the table name for this object.
        Also defines the default ordering for this object list.
        """
        db_table = 'students'
        ordering = ['student_id']

    student_id = IntegerField(primary_key=True)
    first_name = CharField(max_length=200)
    last_name = CharField(max_length=200)
    stud_pic = ImageField(upload_to='student_pics', blank=True)
    courses = ManyToManyField(Course)

    def __unicode__(self):
        """
        String representation of the object.
        :return: Return the string form of the object.
        """
        return self.first_name + " " + self.last_name

    def get_absolute_url(self):
        """
        Returns the URL for this object (to show student details).
        :return: URL that shows the details for instructor object.
        """
        return reverse('student_details', kwargs={'pk': self.pk})

    def pic_or_default(self):
        """
        Method that returns an appropriate image for the student.
        If the image is available, returns that image, otherwise,
        returns the default image.
        :return: Image to display for the student.
        """
        if self.stud_pic:
            return self.stud_pic.url
        return MEDIA_URL+'student_pics/default.png'

    def course_list(self):
        """
        Get the list of courses that every student takes.
        :return: List of courses in csv format.
        """
        course_list = list()
        for course in self.courses.all():
            course_list.append(course.course_name)
        return ', '.join(course_list)


class PhoneNumber(Model):
    """
    Phone number. Students can have multiple phone numbers.
    """
    area_code = DecimalField(max_digits=3, decimal_places=0)
    first_three = DecimalField(max_digits=3, decimal_places=0)
    last_four = DecimalField(max_digits=4, decimal_places=0)
    student = ForeignKey(Student, null=True)

    class Meta:
        db_table = "phone_numbers"

    def __unicode__(self):
        return '({}) {}-{}'.format(self.area_code, self.first_three, self.last_four)


class Scorecard(Model):
    """
    Model to store the student's scores in the courses that the student has taken.
    """
    class Meta:
        """
        Define the table name for storing this model in db.
        """
        db_table = 'scorecard'
    course = ForeignKey(Course)
    student = ForeignKey(Student)
    score = DecimalField(max_digits=5, decimal_places=2)
    passed = BooleanField()


class Instructor(Model):
    """
    Model to store which instructor offers what course.
    """
    class Meta:
        """
        Define the table name for storing this model in db.
        """
        db_table = 'instructors'
    first_name = CharField(max_length=200)
    last_name = CharField(max_length=200)
    course_offered = ManyToManyField(Course, blank=True)

    def __unicode__(self):
        """
        String representation of the object.
        :return: Unicode representation of the object.
        """
        return self.first_name + " " + self.last_name

    def get_absolute_url(self):
        """
        Return the url to display this models details.
        :return: Link to display the details for this instructor's pk.
        """
        return reverse('instructor_edit', kwargs={'pk': self.pk})

    def course_list(self):
        """
        List of courses that this instructor offers.
        :return: List in csv format of the courses offered by this instructor.
        """
        course_list = list()
        for course in self.course_offered.all():
            course_list.append(course.course_name)
        return ", ".join(course_list)

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tutorial Project</title>

    {# Bootstrap CDN #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href={% url 'welcome' %}>Tutorial Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="studentDropDown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Students
                </a>
                <div class="dropdown-menu" aria-labelledby="studentDropDown">
                    <a class="dropdown-item" href={% url 'student_list' %}>Browse Students</a>
                    <a class="dropdown-item" href={% url 'student_add' %}>Add Student</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="instructorDropDown" role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Instructors
                </a>
                <div class="dropdown-menu" aria-labelledby="instructorDropDown">
                    <a class="dropdown-item" href={% url 'instructor_list' %}>Browse Instructors</a>
                    <a class="dropdown-item" href={% url 'instructor_add' %}>Add Instructor</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'course_list' %}" role="button"
                   aria-haspopup="true" aria-expanded="false">
                    Courses
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="deptDropDown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Departments
                </a>
                <div class="dropdown-menu" aria-labelledby="deptDropDown">
                    <a class="dropdown-item" href={% url 'dept_list' %}>Browse Departments</a>
                    <a class="dropdown-item" href={% url 'dept_add' %}>Add Departments</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'phone_view' pk=7 %}" id="PhoneNumber" role="button"
                   aria-haspopup="true" aria-expanded="false">
                    Phones
                </a>
            </li>

        </ul>

    </div>
</nav>
{% block content %}
    {#  CONTENT HERE.  #}
{% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
{% block js %}

    <script src="{% static 'js/base.js' %}"></script>

{% endblock js %}
</body>
</html>